In [1]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])

# Vectorized - no loop needed
y = 2*x + 5

print("x:", x)
print("y = 2x+5:", y)

x: [1 2 3 4 5]
y = 2x+5: [ 7  9 11 13 15]


In [2]:
import numpy as np

marks = np.array([40, 55, 62, 70, 81, 90])

# lecturer adds 5 marks
adjusted = marks + 5
percentage = marks / 100

print("marks:", marks)
print("adjusted +5:", adjusted)
print("percentage:", percentage)

# Task 2 - standardization  z = (x - mean) / std
z = (marks - np.mean(marks)) / np.std(marks)

print("\nz-scores:", z)
print("mean of z:", np.mean(z))  # should be ~0
print("std of z:", np.std(z))    # should be 1

marks: [40 55 62 70 81 90]
adjusted +5: [45 60 67 75 86 95]
percentage: [0.4  0.55 0.62 0.7  0.81 0.9 ]

z-scores: [-1.59799895 -0.68774638 -0.26296185  0.22250618  0.89002473  1.43617627]
mean of z: 2.590520390792032e-16
std of z: 1.0


In [3]:
import numpy as np

data = np.array([
    [60, 70, 80],
    [50, 65, 75],
    [90, 85, 95]
])

adjustment = np.array([5, 0, 2])

result = data + adjustment

print("data:\n", data)
print("\nadjustment:", adjustment)
print("\nresult = data + adjustment:\n", result)

data:
 [[60 70 80]
 [50 65 75]
 [90 85 95]]

adjustment: [5 0 2]

result = data + adjustment:
 [[65 70 82]
 [55 65 77]
 [95 85 97]]


In [4]:
import numpy as np

data = np.array([
    [10, 20, 30],
    [20, 30, 40],
    [30, 40, 50]
])

means = data.mean(axis=0)
centered = data - means

print("data:\n", data)
print("\ncolumn means:", means)  # [20. 30. 40.]
print("\ncentered = data - means:\n", centered)

# Task 3 verify
print("\nVerify mean of centered columns:", centered.mean(axis=0))

data:
 [[10 20 30]
 [20 30 40]
 [30 40 50]]

column means: [20. 30. 40.]

centered = data - means:
 [[-10. -10. -10.]
 [  0.   0.   0.]
 [ 10.  10.  10.]]

Verify mean of centered columns: [0. 0. 0.]


In [5]:
import numpy as np
import time

x = np.arange(1_000_000)

# 1. Loop version
start = time.time()
result_loop = []
for value in x:
    result_loop.append(value**2 + 2*value + 1)
loop_time = time.time() - start
print(f"Loop time: {loop_time:.2f} seconds")

# 2. Vectorized version
start = time.time()
result_vectorized = x**2 + 2*x + 1
vec_time = time.time() - start
print(f"Vectorized time: {vec_time:.4f} seconds")

# 3. Check they agree
print("Same result?", np.allclose(result_loop, result_vectorized))
print(f"Speedup: {loop_time / vec_time:.1f}x faster")

Loop time: 0.72 seconds
Vectorized time: 0.0275 seconds
Same result? True
Speedup: 26.2x faster


In [6]:
import numpy as np

def standardize(x):
    return (x - np.mean(x)) / np.std(x)

# Test 1 - small marks
arr1 = np.array([40, 55, 62, 70, 81, 90])
print("arr1:", standardize(arr1))
print("mean:", standardize(arr1).mean(), "std:", standardize(arr1).std())

# Test 2 - random normal 100, 15
np.random.seed(0)
arr2 = np.random.normal(100, 15, 1000)
print("\narr2 sample:", standardize(arr2)[:5])
print("mean:", standardize(arr2).mean(), "std:", standardize(arr2).std())

# Test 3 - 2D? Use axis? For now 1D
arr3 = np.array([10, 20, 30, 40, 50])
print("\narr3:", standardize(arr3))
print("mean:", standardize(arr3).mean(), "std:", standardize(arr3).std())

arr1: [-1.59799895 -0.68774638 -0.26296185  0.22250618  0.89002473  1.43617627]
mean: 2.590520390792032e-16 std: 1.0

arr2 sample: [1.83307829 0.4512654  1.0374471  2.31618349 1.93794371]
mean: -9.00612917575927e-16 std: 1.0

arr3: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
mean: 0.0 std: 0.9999999999999999
